language: ruby
notifications:
  email: false
rvm:
  - 1.9.3 # Same as Ariadne host env
install: bundle install --without default
script: 
  - bundle exec foodcritic cookbooks-override/* -I test/support/foodcritic/* -t '~CINK001' -t '~FC011' -t '~FC031' --epic-fail ''
