---
basebox: lucid64
project: example
branch: develop
memory: 1000
cpu_count: 2

# If building an install profile according to Myplanet layout assumptions,
# enter its repository URL here. (Otherwise, leave blank.)
repo_url: ''
